name: Validate Metadata
on: [push, workflow_dispatch]
jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: metadata validation
        uses: biobricks-ai/github-actions/metadata-check@main